// curiosity-data.js
// Auto-updated 2026-03-31 — do not edit manually

var CURIOSITY_DATA = {
  date: "2026-03-31",
  mainArticle: {
    title: "The Library That Burned the World Into Memory",
    subtitle: "How the destruction of the Great Library of Alexandria became history's most enduring cautionary tale — and why much of what we think we know about it is wrong.",
    image: "https://images.pexels.com/photos/1807091/pexels-photo-1807091.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    readTime: "9 min",
    content: [
      { type: "paragraph", text: "No single building in the ancient world haunts the modern imagination quite like the Great Library of Alexandria. Founded in the third century BCE under the Ptolemaic dynasty of Egypt, it was conceived as nothing less than a universal repository of all human knowledge — every scroll, every treatise, every poem that could be gathered from the known world. Its destruction has been invoked for centuries as shorthand for catastrophic intellectual loss, a wound from which civilization supposedly never fully recovered. Yet the true story of the Library is far more complex, more fascinating, and more instructive than the simple narrative of a single, apocalyptic fire." },
      { type: "heading", text: "A Kingdom Built on Knowledge" },
      { type: "paragraph", text: "When Ptolemy I Soter, one of Alexander the Great's most capable generals, carved Egypt out of the collapsing Macedonian empire around 305 BCE, he understood that military power alone could not sustain a dynasty. He needed cultural legitimacy, and he found it in the idea of assembling the world's knowledge in his capital city. Working alongside the Athenian exile Demetrius of Phalerum, Ptolemy established the Mouseion — a scholarly complex dedicated to the Muses — and within it, the famous Library. Ships arriving in Alexandria's harbor were reportedly searched, and any scrolls found aboard were copied; sometimes the originals were kept, and the copies returned to their bewildered owners." },
      { type: "heading", text: "The Scale of Ambition" },
      { type: "paragraph", text: "At its height, ancient sources claim the Library held between 400,000 and 700,000 scrolls, though modern scholars debate these figures fiercely. What is certain is that it attracted some of the greatest minds of the ancient Mediterranean: Euclid formalized geometry there, Eratosthenes calculated the circumference of the Earth with startling accuracy, and Aristarchus proposed a heliocentric model of the solar system seventeen centuries before Copernicus. The Library was not merely a warehouse of papyrus but a living research institution, complete with lecture halls, gardens, a zoo, and communal dining where scholars debated ideas over meals funded by the Ptolemaic state. It represented an extraordinary experiment in state-sponsored intellectual life, one that would not be rivaled in scope for over a millennium." },
      { type: "heading", text: "Death by a Thousand Cuts" },
      { type: "paragraph", text: "The popular image of the Library consumed in a single dramatic conflagration is almost certainly a myth. Julius Caesar's military operations in Alexandria in 48 BCE likely destroyed a warehouse of scrolls near the harbor, not the Library itself. Over the following centuries, the institution suffered a slow decline driven by political upheaval, reduced royal patronage, sectarian violence, and the general erosion of Ptolemaic and then Roman support for pagan scholarship. The philosopher Hypatia, brutally murdered by a Christian mob in 415 CE, is sometimes treated as a symbol of the Library's final death, though by her time the great collection had likely been dispersed or degraded for generations." },
      { type: "heading", text: "What Was Actually Lost?" },
      { type: "paragraph", text: "Historians have long debated just how much irreplaceable knowledge vanished with the Library's decline. We know that entire bodies of literature — most of Sappho's poetry, the lost plays of Sophocles and Euripides, treatises by pre-Socratic philosophers — survived only in fragments or not at all. Yet attributing all these losses solely to Alexandria oversimplifies the messy reality of ancient textual transmission, where copying errors, neglect, war, and changing tastes destroyed works across hundreds of libraries throughout the Mediterranean. The Library of Alexandria was the largest single node in an imperfect network of knowledge preservation, but it was never the only one." },
      { type: "heading", text: "The Myth as Mirror" },
      { type: "paragraph", text: "What makes the Library's story so persistent is not the historical details but what it symbolizes for each era that retells it. Enlightenment thinkers wielded it as a weapon against religious intolerance, blaming fanatical mobs for the destruction of rational inquiry. Cold War intellectuals saw in it a warning about totalitarianism's hostility to free thought. In the digital age, the Library has been reborn as metaphor yet again — the Internet Archive explicitly styles itself as a modern Alexandria, and anxieties about data loss, censorship, and platform collapse echo ancient fears about the fragility of accumulated knowledge." },
      { type: "paragraph", text: "The Ptolemies' grand experiment reminds us that knowledge is never safe simply because it has been recorded. Preservation requires active, ongoing commitment — institutional funding, political will, and a culture that values inquiry over expedience. Every generation must choose to maintain the infrastructure of learning or watch it erode through indifference, which is a fate far more common and far more insidious than any dramatic fire. The Great Library of Alexandria did not burn in a single night; it faded, and that slower story carries a warning more urgent than any myth." }
    ]
  },
  personOfTheDay: {
    name: "Ibn Battuta",
    lifespan: "1304–1368",
    category: "Exploration & Travel",
    image: "https://images.pexels.com/photos/36772038/pexels-photo-36772038.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    bio: "Abu Abdullah Muhammad ibn Battuta was born in Tangier, Morocco, in 1304 into a family of Islamic legal scholars. At the age of twenty-one, he set out on the hajj to Mecca — a journey that would stretch into nearly three decades of almost continuous travel across the known world. By the time he returned home for good, he had visited the equivalent of more than forty modern nations, covering an estimated 75,000 miles, a distance unmatched by any known traveler until the age of steam.\n\nIbn Battuta's journeys took him from the courts of West African kings to the steppes of Central Asia, from the Malabar Coast of India to the islands of Southeast Asia and possibly the coast of China. He served as a qadi — an Islamic judge — in the Sultanate of Delhi for several years, survived shipwrecks, encountered the Black Death sweeping through Syria, and navigated the political intrigues of dozens of rulers eager to employ a well-traveled scholar. His observations on trade routes, religious practices, architectural wonders, and local customs provide an irreplaceable window into the fourteenth-century Islamic world and the civilizations at its edges.\n\nUpon his final return to Morocco around 1354, Sultan Abu Inan Faris commissioned the young scholar Ibn Juzayy to compile Ibn Battuta's oral accounts into a written work known as the Rihla, meaning \"The Journey.\" Though some modern historians question certain claims — particularly regarding his supposed visit to China — the Rihla remains one of the most important travel documents in human history. Ibn Battuta died in Morocco around 1368, largely forgotten for centuries until European scholars rediscovered his work in the nineteenth century and recognized him as one of the greatest explorers who ever lived."
  },
  onThisDay: {
    headline: "The Eiffel Tower Is Officially Completed",
    date: "March 31, 1889",
    summary: "On March 31, 1889, the Eiffel Tower was officially completed in Paris after just over two years of construction, making it the tallest man-made structure in the world at 984 feet. Gustave Eiffel himself climbed the 1,710 steps to the summit and unfurled a French tricolor flag, while cannons fired a salute from below. The tower had been built as the entrance arch for the 1889 Exposition Universelle, a world's fair celebrating the centennial of the French Revolution.\n\nThe structure had faced fierce opposition from many of Paris's most prominent artists and intellectuals during its construction. A petition signed by figures including Guy de Maupassant and Charles Gounod denounced it as a \"metal asparagus\" and a disgrace to the city's skyline. Yet within months of the fair's opening, the tower had welcomed nearly two million visitors, and it quickly became the most recognizable symbol of Paris and of modern engineering ambition — a status it has never relinquished.",
    image: "https://images.pexels.com/photos/32319650/pexels-photo-32319650.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
  }
};
