// curiosity-data.js
// Auto-updated 2026-03-30 — do not edit manually

var CURIOSITY_DATA = {
  date: "2026-03-30",
  mainArticle: {
    title: "The Tsar in Disguise: Peter the Great's Secret Journey Through Europe",
    subtitle: "In 1697, the most powerful man in Russia disguised himself as a carpenter to learn how the West built its ships — and came home to transform an empire.",
    image: "https://images.pexels.com/photos/30917889/pexels-photo-30917889.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    readTime: "6 min",
    content: [
      { type: "paragraph", text: "In the spring of 1697, a delegation of 250 Russians set out westward across Europe under the banner of the Grand Embassy. Officially, the mission sought military allies against the Ottoman Empire. But buried within the convoy, traveling under the alias 'Pyotr Mikhailov' and listed as a junior official, was Tsar Peter I of Russia — a towering, restless man of twenty-four who had already decided that his country was a century behind the West and intended to do something about it personally." },
      { type: "heading", text: "A Tsar Among Shipwrights" },
      { type: "paragraph", text: "Peter's first destination of real consequence was the Dutch port of Zaandam, then the shipbuilding capital of the world, its skyline a forest of windmills and masts. He enrolled under his alias at the VOC yards in Amsterdam, picking up an adze and working alongside ordinary carpenters who — for a time at least — had no idea they were laboring beside an absolute monarch. The secret barely lasted weeks before crowds gathered to stare, forcing Peter to move operations and eventually decamp for England." },
      { type: "heading", text: "Lessons in England and the Architecture of Power" },
      { type: "paragraph", text: "In England, Peter was hosted by King William III and granted access to the Royal Observatory at Greenwich, the Royal Mint — then run by Isaac Newton — and the dockyards at Deptford, where he reportedly caused ruinous damage to the house lent to him. He attended Parliament, watched anatomical dissections with unsettling enthusiasm, and recruited hundreds of engineers, naval officers, and craftsmen to return with him to Russia. What Peter was absorbing was not merely technical knowledge but a model of institutional power: how a modern state could systematize expertise and deploy it as an instrument of national strength." },
      { type: "heading", text: "The Revolution Imposed From Above" },
      { type: "paragraph", text: "Peter returned to Russia in August 1698 to find a Streltsy rebellion in progress, which he suppressed with characteristic ferocity before turning to the work of transformation. The Julian calendar was replaced, the Russian Orthodox Church restructured, and the old boyar aristocracy were famously shorn of their beards by imperial decree. New schools, a new navy, a new capital — Saint Petersburg, driven into Baltic marshland by conscripted labor — and a new designation for the state itself, the Russian Empire, all flowed from eighteen months of careful watching." },
      { type: "heading", text: "The Meaning of the Journey" },
      { type: "paragraph", text: "The Grand Embassy remains one of history's most extraordinary exercises in statecraft by immersion, a ruling autocrat voluntarily apprenticing himself to the knowledge of another civilization. No other European monarch of the era did anything remotely comparable, and the sheer strangeness of the act reflects Peter's conviction that prestige without capability was hollow. His reforms were brutal in execution and contradictory in spirit — a modernizing autocracy is still an autocracy — but the directness of the causal chain, from one man's curiosity to an empire's reinvention, is almost without parallel in the historical record." },
      { type: "paragraph", text: "Whether Peter's revolution ultimately liberated Russia or simply imposed a new form of coercion dressed in Western costume is a debate that has never been fully resolved. What is not in doubt is the scale of the wager he made: that the survival of Russia depended on competing with Europe on Europe's own terms, learned at first hand, in its dockyards and laboratories and parliaments. That a single journey of eighteen months could redirect the destiny of the world's largest country is a testament to something the modern era often underestimates — the unreasonable, world-altering power of one person's will to learn." }
    ]
  },
  personOfTheDay: {
    name: "Vincent van Gogh",
    lifespan: "1853–1890",
    category: "Art",
    image: "https://images.pexels.com/photos/3720778/pexels-photo-3720778.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    bio: "Vincent Willem van Gogh was born on March 30, 1853, in Zundert, a small village in the Dutch province of Noord-Brabant, the son of a Protestant minister. He spent his twenties drifting through failed careers — art dealer, schoolteacher, lay preacher among the miners of the Borinage — before arriving at painting in his late twenties with the convert's all-consuming intensity. His early Dutch work was dark and earthbound, culminating in The Potato Eaters (1885), a portrait of peasant life rendered in the colors of soil.\n\nMoving to Paris in 1886 brought Van Gogh into contact with the Impressionists and Post-Impressionists, and the encounter electrified his palette. He adopted the broken brushwork and vivid chromaticism of his contemporaries, then pushed far beyond them into something more turbulent and emotionally direct. The years in the south of France — first in Arles, then confined to the Saint-Rémy asylum — produced Sunflowers, The Night Café, and The Starry Night at a rate of productivity that bordered on frenzy, even as his mental health broke down around him.\n\nVan Gogh died on July 29, 1890, at thirty-seven, two days after shooting himself in a wheat field outside Auvers-sur-Oise, having sold only a single painting in his lifetime. Within decades he would be recognized as one of the defining influences on modern art, and his letters — frank, searching, and genuinely beautiful — are read as a literary masterwork in their own right. The tragedy of his life has sometimes obscured the more remarkable fact: that in barely ten years of serious work, he produced over two thousand paintings and drawings of shattering originality."
  },
  onThisDay: {
    headline: "SEWARD'S FOLLY: AMERICA BUYS ALASKA FOR TWO CENTS AN ACRE",
    date: "March 30, 1867",
    summary: "In the early hours of March 30, 1867, Secretary of State William H. Seward and Russian minister Eduard de Stoeckl signed the treaty by which the United States agreed to purchase Alaska from the Russian Empire for $7.2 million — roughly two cents per acre for 586,412 square miles of Arctic territory. The negotiation had begun the previous evening; Stoeckl arrived at Seward's Washington home to find the Secretary mid-game of whist, who reportedly swept the cards aside and declared that the State Department could be opened that very night. The treaty was signed before dawn.\n\nThe American press responded with open mockery. Newspapers christened the acquisition 'Seward's Folly,' 'Seward's Icebox,' and 'Walrussia' — a frozen wasteland of polar bears and permafrost that no sensible nation would want. Critics in Congress questioned why the United States would spend millions on a distant Arctic wilderness while the country was still binding the wounds of the Civil War. The Senate ratified the treaty, but the House delayed appropriating the purchase funds for over a year, deeply skeptical that any return could justify the outlay.\n\nHistory rendered a very different verdict. The Klondike gold rush of 1896 and subsequent Alaskan gold strikes alone dwarfed the original purchase price many times over. The territory's strategic importance became undeniable in 1942 when Japanese forces occupied the Aleutian islands of Attu and Kiska, confirming that Alaska sat astride the Pacific's northern approaches. When Alaska became the 49th state in 1959, its reserves of oil, natural gas, fish, timber, and minerals had long since transformed Seward's Folly into what many economists consider the most consequential real estate transaction in American history.",
    image: "https://images.pexels.com/photos/18482092/pexels-photo-18482092.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
  }
};
