// rics-data.js
// Auto-updated 2026-04-11 — do not edit manually

var RICS_DATA = {
  date: "2026-04-11",
  topic: "S106 Renegotiation and Viability Review Mechanisms in Affordable Housing Delivery",
  module: "Planning and Development Management",
  level: 3,
  apc_competency: "Planning and Development Management (Level 3)",
  focus: "This lesson examines the procedural and technical framework for renegotiating S106 agreements on affordable housing grounds, including viability review mechanisms (early, mid-point, and late-stage), the role of the District Valuer, and how housing associations like Latimer navigate these processes to protect affordable unit delivery. Essential knowledge for APC candidates advising on planning obligations in RP-led schemes.",
  image: "https://images.unsplash.com/photo-1460317442991-0ec209397118?w=1200&auto=format&fit=crop",
  content: [
    { type: "paragraph", text: "Section 106 agreements remain the primary mechanism for securing affordable housing delivery through the planning system. However, the period between outline consent and build-out on phased schemes can span years — during which costs, values, policy, and grant availability shift materially. For a housing association developer like Latimer by Clarion, understanding when and how S106 obligations can be renegotiated, and the viability review mechanisms embedded within them, is critical to protecting both scheme viability and the organisation's social purpose of maximising affordable homes." },
    { type: "heading", text: "The Legal Basis for S106 Renegotiation" },
    { type: "paragraph", text: "Section 106A of the Town and Country Planning Act 1990 (as amended) permits any person bound by a planning obligation to apply to the LPA for modification or discharge after five years from the date of the obligation. However, in practice, most renegotiations occur by mutual agreement between the developer and LPA, often triggered by a viability review clause within the original S106 itself. The 2023 NPPF (and subsequent 2024 revisions) confirmed that the weight of viability evidence in plan-making should reduce the need for site-specific viability arguments at application stage, but review mechanisms remain standard on large phased sites." },
    { type: "key_term", term: "Viability Review Mechanism (VRM)", text: "A contractual clause within a S106 agreement that requires the developer to submit an updated viability appraisal at a defined trigger point (e.g. before commencement of a later phase, or upon achieving a certain percentage of sales). The VRM tests whether improved scheme economics enable delivery of additional affordable housing above the consented baseline, or conversely whether a reduction is justified. VRMs are sometimes called 'clawback' or 'upward-only' review clauses depending on their direction of travel." },
    { type: "paragraph", text: "There are three common types of VRM encountered in London and wider England: (1) Early-stage reviews — triggered if a scheme has not commenced within a specified period (typically 2-3 years) after consent, requiring a fresh appraisal before starting; (2) Mid-point reviews — triggered at a defined phase boundary or percentage completion, common on schemes of 150+ units; (3) Late-stage reviews — triggered near the end of a scheme, reconciling actual costs and revenues against the original appraisal assumptions. The Greater London Authority's Affordable Housing and Viability SPG (2017, updated 2023) codified the 'Fast Track' and 'Viability Tested' routes, with the latter mandating early and late-stage reviews as a minimum." },
    { type: "heading", text: "How VRMs Work in Practice: The RP Developer Perspective" },
    { type: "paragraph", text: "At Latimer, when acquiring land for a phased scheme with a VRM attached, the development team must model not just the consented affordable housing quantum but also plausible upside and downside scenarios at each review point. This feeds directly into the land acquisition appraisal — if there is a realistic prospect that a late-stage review could require additional affordable units beyond the consented baseline, the land bid must account for this contingent liability. Conversely, if the VRM is 'upward only' (i.e. affordable housing can only increase, never decrease), the risk profile differs from a 'two-way' review." },
    { type: "callout", label: "APC Tip — Worked Example", text: "Scenario: Latimer acquires Phase 2 of a 400-unit mixed-tenure scheme in outer London. The original S106 secured 35% affordable housing (140 units) via the Fast Track route with no VRM. However, the vendor's Phase 1 delivery was delayed, and the LPA now requires a Viability Tested Route for Phase 2 with an early-stage and late-stage review. The early-stage review is triggered pre-commencement. The original appraisal assumed build costs of £2,850/sqft; current costs are £3,250/sqft. Homes England AHP grant of £60,000/unit was not in the original appraisal but is now available. The review must reflect current inputs: updated build costs, updated sales values (GDV up 8%), the grant, and current benchmark land value (using the EUV+ methodology). The surplus or deficit against the original appraisal determines whether the 35% baseline is maintained, increased, or — if the review is two-way — reduced. As the RP developer, Latimer would argue that grant should not simply replace S106 obligations (i.e. grant should be additional, enabling more affordable units or deeper affordability, not subsidising the landowner's receipt). This is a key negotiation point with LPAs and one assessors will expect you to articulate clearly." },
    { type: "heading", text: "The Role of the District Valuer and Independent Review" },
    { type: "paragraph", text: "Most S106 VRM clauses specify that the updated appraisal will be scrutinised by an independent assessor — commonly the District Valuer Services (DVS), part of the Valuation Office Agency. The DVS acts for the LPA and interrogates the developer's submitted Financial Viability Appraisal (FVA). Key areas of challenge include: the developer's assumed profit margin (typically 15-20% on cost for affordable housing, 17.5-20% on GDV for market housing), benchmark land value methodology, abnormal cost claims, and the treatment of grant funding. For Latimer, it is essential that the FVA is prepared to RICS Professional Standard on Financial Viability in Planning (effective 2021, updated 2024) and that all assumptions are evidenced and defensible." },
    { type: "key_term", term: "Benchmark Land Value (BLV)", text: "The threshold land value against which scheme viability is tested. Under current NPPF/PPG guidance, BLV should be established using the Existing Use Value Plus (EUV+) approach, reflecting the landowner's reasonable return above current use value. The 'plus' premium varies by context but should not reflect 'hope value' derived from the planning permission itself. For RP-led schemes on public land, the premium may be minimal or zero." },
    { type: "paragraph", text: "A common area of dispute in VRM negotiations is whether the BLV should be re-tested at the review point or fixed at the original appraisal level. If BLV is re-tested and land values have risen, the developer may argue that viability has not improved sufficiently to deliver more affordable housing — effectively capturing land value uplift as landowner return rather than public benefit. LPAs and DVS increasingly insist that BLV is fixed at the consented level to prevent this outcome. Latimer's approach should be to agree a fixed BLV at S106 negotiation stage and ensure this is clearly drafted in the review mechanism wording." },
    { type: "heading", text: "Grant Funding and S106 Interaction: Additionality vs Substitution" },
    { type: "paragraph", text: "A critical issue for housing associations is how Homes England Affordable Housing Programme (AHP) grant interacts with S106 obligations during viability reviews. The principle of 'additionality' holds that grant should be used to deliver affordable housing beyond what the planning system would secure without grant — for example, converting shared ownership units to social rent, or increasing the overall percentage. If grant is treated as a developer input that simply improves viability, the review mechanism may claw back the benefit as additional affordable housing obligation, or worse, the LPA may argue that the S106 baseline should have been higher. Latimer must be precise in its appraisals about whether grant is modelled as a viability input or as an additionality tool. Homes England's own guidance (Strategic Partnership and CME framework) expects grant to deliver additional homes or deeper affordability, not to substitute for planning policy requirements." },
    { type: "callout", label: "APC Tip — Assessor Angle", text: "An assessor may ask: 'If your scheme secures 35% affordable via S106 and you then layer in Homes England grant, how do you ensure additionality?' A strong answer would explain: (1) you ring-fence the S106 baseline affordable units as 'policy compliant' with no grant; (2) you then use grant to convert tenure (e.g. shared ownership to London Affordable Rent) or to fund additional units above the 35%; (3) you ensure the FVA presented at viability review excludes grant from the S106 baseline test but includes it in the overall delivery model. This demonstrates both technical competence and ethical practice — the dual obligation to Homes England conditions and planning policy." },
    { type: "heading", text: "Drafting Pitfalls in S106 Viability Review Clauses" },
    { type: "paragraph", text: "From a practitioner perspective, the quality of the VRM drafting in the S106 can make or break an RP's position at review. Common pitfalls include: (a) ambiguous trigger points — e.g. 'prior to commencement' without defining whether this means commencement of the entire phase or enabling works; (b) failure to specify the appraisal methodology (RICS GN or otherwise); (c) no time limit for the LPA's review, leading to delays; (d) no cap on the affordable housing uplift (meaning the developer could theoretically be required to deliver 100% affordable if values rise dramatically); (e) no dispute resolution mechanism — if the developer and DVS disagree, there is no escalation route. Latimer's legal and development teams should use standardised VRM templates and push for clear definitions on all of these points at the heads of terms stage." },
    { type: "key_term", term: "Clawback / Overage", text: "A financial mechanism, often distinct from a VRM, where a proportion of any surplus (actual GDV minus actual costs minus agreed profit and BLV) is paid to the LPA or used to fund additional affordable units. Clawback is typically triggered at late-stage review on completion of a phase. The split of surplus (e.g. 60% to additional affordable housing, 40% to the developer) is negotiated and specified in the S106." },
    { type: "paragraph", text: "For Latimer, the critical commercial question at land acquisition is: what is the maximum affordable housing obligation that could crystallise across all VRM trigger points, and can the scheme still support the proposed land price and required RP hurdle rate (IRR or margin on cost) under that scenario? Sensitivity testing on the appraisal — running the 'worst case VRM outcome' — is essential pre-acquisition due diligence. This is a Level 3 competency demonstration: advising the business on risk, not just calculating numbers." },
    { type: "heading", text: "Recent Policy Context" },
    { type: "paragraph", text: "The Levelling Up and Regeneration Act 2023 signalled the eventual replacement of S106/CIL with an Infrastructure Levy (IL) in England. However, as of early 2026, the IL remains in the testing phase and S106 continues to be the primary affordable housing delivery mechanism. The transitional uncertainty itself is a viability consideration — LPAs may be more willing to embed robust VRMs knowing that the policy landscape is shifting. Candidates should be aware that the NPPF (December 2024 revision) reinforced that viability assessments should be proportionate and that VRMs should not be used to delay decision-making or delivery." }
  ],
  summary: [
    "S106 viability review mechanisms (VRMs) are standard on phased schemes — understand the three types (early, mid-point, late-stage) and their trigger definitions.",
    "Benchmark Land Value should be fixed at the consented appraisal level to prevent landowner capture of value uplift at review — push for this in S106 drafting.",
    "Homes England grant must be treated as additional to S106 obligations, not a substitute — ring-fence S106 baseline affordable units separately in your appraisal.",
    "Pre-acquisition sensitivity testing must model the 'worst case VRM outcome' (maximum affordable housing uplift across all review triggers) to protect the RP's hurdle rate.",
    "Drafting quality of VRM clauses is critical — specify methodology, trigger definitions, time limits, surplus split, caps, and dispute resolution at heads of terms stage."
  ],
  qa: [
    { q: "How would you advise your board on the risk of a late-stage viability review clause in a S106 on a 300-unit phased scheme?", a: "I would model the late-stage review scenario by running the appraisal with current costs and projected sales values at the likely review date. I would test the surplus/deficit against the fixed BLV and consented profit margin. If the scheme shows a surplus, I would calculate the additional affordable units that could be required under the clawback split specified in the S106 — for example, if the split is 60:40 and the surplus is £2.4m, the additional affordable housing obligation is £1.44m worth of units. I would present the board with three scenarios (base case, upside, downside) showing the impact on IRR and margin on cost, and recommend a maximum land bid that remains viable under the worst case. I would also flag any drafting weaknesses in the VRM clause — such as an uncapped uplift — and recommend legal amendments before exchange." },
    { q: "What is the difference between a 'clawback' mechanism and an 'upward-only' viability review, and why does the distinction matter for an RP developer?", a: "A clawback mechanism is financial — it requires the developer to pay a share of any surplus to the LPA or apply it to additional affordable housing at late stage. An 'upward-only' VRM is a policy tool that allows the affordable housing percentage to increase if viability improves but cannot reduce below the consented baseline. The distinction matters because a clawback may result in a cash payment rather than physical additional units, which can be preferable for an RP if late in the build programme. Conversely, an upward-only VRM may require delivery of additional physical units, affecting design, tenure mix, Homes England grant conditions, and handover timelines. In either case, the RP must model the contingent liability at land acquisition." },
    { q: "How should Homes England AHP grant be treated in a viability review appraisal, and what is the risk if it is treated incorrectly?", a: "Grant should be excluded from the S106 viability review appraisal for the baseline affordable housing obligation. It should be presented as an additional funding source that enables enhanced outcomes — either more units or deeper affordability tenures (e.g. social rent instead of shared ownership). If grant is included as a viability input in the FVA, the DVS or LPA may conclude that the scheme can support more affordable housing than the consented level, effectively using public subsidy to increase the S106 obligation rather than deliver genuine additionality. This would breach Homes England's funding conditions, which require grant to be additional, and could jeopardise the Strategic Partnership. The correct approach is to run the S106 review appraisal without grant, agree the planning obligation, and then separately layer grant to improve the tenure mix." },
    { q: "What is the RICS-recommended approach to establishing Benchmark Land Value in a viability review, and how does this apply on public sector land disposals to RPs?", a: "The RICS Financial Viability in Planning guidance (2021, updated 2024) and the NPPF/PPG require BLV to be assessed using the Existing Use Value Plus (EUV+) methodology. EUV is the value of the site in its current lawful use, and the 'plus' is a landowner premium sufficient to incentivise release. On public sector land — for example, a local authority disposing to Latimer — the premium may be minimal or zero, particularly where the public body's objective is maximising affordable housing rather than land receipt. In a viability review, the BLV should be fixed at the level agreed in the original FVA. If the LPA or DVS seeks to re-test BLV at market value or using comparable transactions inflated by hope value, this should be robustly challenged as inconsistent with policy." },
    { q: "Can you give an example from your experience where the drafting of a S106 viability review clause caused a problem, and how you resolved it?", a: "On a 200-unit phased scheme in the East of England, the S106 VRM trigger was defined as 'prior to commencement of Phase 2' but did not specify whether enabling works (site clearance, access road) constituted commencement. The LPA argued that enabling works triggered the review, but the appraisal inputs at that stage were based on pre-tender estimates. We engaged with the LPA planning officer and their legal team, referencing the TCPA 1990 definition of 'material operation' and arguing that the VRM should be triggered at reserved matters approval for Phase 2, when cost and value certainty was higher. We agreed a deed of variation to clarify the trigger as 'approval of the first reserved matters application for Phase 2'. The lesson was that at heads of terms stage, the development team must specify VRM triggers with precision and cross-reference to defined terms in the S106, avoiding reliance on generic planning terminology." }
  ],
  news: [
    { tag: "S106 / Viability", headline: "DLUHC Publishes Updated Viability PPG Guidance Ahead of Infrastructure Levy Rollout", body: "The Department for Levelling Up, Housing and Communities published revised Planning Practice Guidance on viability in March 2026, clarifying the treatment of grant funding in viability reviews and reinforcing the EUV+ approach to benchmark land value. The update is seen as a stopgap measure as the Infrastructure Levy pilot programme continues in ten test areas across England." },
    { tag: "Affordable Housing", headline: "Clarion Housing Group Reports Record Affordable Completions for 2025/26", body: "Clarion Housing Group, parent of Latimer, reported delivery of over 3,200 affordable homes in the 2025/26 financial year, its highest ever annual figure. The group credited its Strategic Partnership with Homes England and effective use of S106 viability review mechanisms to increase affordable housing percentages on several phased sites above the originally consented baseline." },
    { tag: "Planning Reform", headline: "Infrastructure Levy Pilot Authorities Flag Concerns Over Affordable Housing In-Kind Delivery", body: "Three of the ten Infrastructure Levy pilot local authorities have raised concerns that the proposed levy mechanism may deliver fewer affordable homes in-kind than the current S106 system. A joint letter to the Housing Minister warned that monetising affordable housing obligations via a levy risks creating a 'delivery gap' where funds are collected but units are not built on-site. Housing associations including L&Q and Peabody have echoed these concerns." }
  ]
};
