// rics-data.js
// Auto-updated 2026-04-10 — do not edit manually

var RICS_DATA = {
  date: "2026-04-10",
  topic: "S106 Viability Review Mechanisms: Late-Stage Reviews in Affordable Housing Schemes",
  module: "Planning and Development Management",
  level: 3,
  apc_competency: "Planning and Development Management (Level 3)",
  focus: "This lesson examines the mechanics, triggers, and negotiation strategies for late-stage (near-completion) S106 viability review mechanisms in affordable housing-led developments. Understanding these clauses is critical for housing associations like Latimer/Clarion that must protect affordable housing delivery while navigating LPA requirements for upward-only review provisions.",
  image: "https://images.unsplash.com/photo-1460317442991-0ec209397118?w=1200&auto=format&fit=crop",
  content: [
    { type: "paragraph", text: "Section 106 agreements increasingly contain viability review mechanisms (VRMs) — sometimes called 'review clauses' or 'clawback provisions' — that allow local planning authorities to reassess the quantum of affordable housing or financial contributions at defined trigger points during a scheme's lifecycle. For a housing association development arm like Latimer by Clarion, these clauses have profound implications for scheme viability, grant funding assumptions, and the tenure mix ultimately delivered. This lesson focuses specifically on late-stage reviews (typically triggered at 75-90% of private unit sales or practical completion) and how to manage them in practice." },
    { type: "heading", text: "What Is a Late-Stage Viability Review Mechanism?" },
    { type: "paragraph", text: "A late-stage review is a contractual mechanism within a S106 agreement that requires the developer to submit an updated viability appraisal close to scheme completion. The purpose is to capture any uplift in actual revenues or cost savings compared to the assumptions in the original (pre-permission) viability assessment, and to redistribute a defined proportion of that surplus as additional affordable housing or commuted sum payments. Late-stage reviews sit alongside (or instead of) early-stage reviews, which typically trigger before a defined phase commences. The Mayor of London's Affordable Housing and Viability SPG (2017, updated 2023) formalised these in the 'Fast Track' and 'Viability Tested' routes, and many London boroughs and increasingly non-London LPAs now mandate them." },
    { type: "key_term", term: "Viability Review Mechanism (VRM)", text: "A clause in a S106 agreement requiring a developer to resubmit an updated financial appraisal at defined trigger points. It compares actual outturn costs and revenues against the assumptions in the original viability assessment to determine whether additional affordable housing or financial contributions should be provided. Also known as a review clause, clawback mechanism, or uplift mechanism." },
    { type: "key_term", term: "Surplus Sharing / Deficit Sharing", text: "The mechanism by which any identified surplus (actual profit exceeding the agreed benchmark profit level) is shared between the developer and the LPA. The London Plan and many borough planning policies specify a 60:40 split (60% to affordable housing, 40% to the developer), though this varies. Deficit sharing (where actual returns fall below the benchmark) is typically not applied — most VRMs are 'upward only', meaning the developer cannot reduce the affordable housing quantum below that secured at planning stage." },
    { type: "heading", text: "Why Late-Stage Reviews Matter for Housing Associations" },
    { type: "paragraph", text: "At Latimer/Clarion, late-stage reviews create a distinctive set of challenges compared to a speculative housebuilder. First, the housing association may be both the affordable housing provider and the applicant/developer. This means the 'surplus' captured by the VRM could paradoxically be redirected away from the RP's own cross-subsidy model. Second, grant funding from Homes England's Affordable Homes Programme (AHP) is typically locked in at contract stage with fixed assumptions on tenure, unit numbers, and grant rates per unit. A VRM that changes the affordable housing mix at a late stage could conflict with AHP grant conditions, potentially requiring a contract variation or grant repayment. Third, the RP's board may have approved the scheme on the basis of a specific internal rate of return (IRR) or net present value (NPV) that assumed the S106 affordable housing package was fixed. A late-stage uplift changes the financial outturn." },
    { type: "callout", label: "APC Tip — Worked Example", text: "Latimer secures planning permission for a 200-unit scheme: 70 affordable (35%) and 130 private sale. The original viability appraisal assumed a GDV for the private units of £52m and total costs of £48m, producing a developer's profit of £4m (7.7% on GDV — below the typical 15-20% benchmark because the RP accepts a lower return). The S106 includes a late-stage VRM triggered at 75% private sales. At review, actual private sales revenues are tracking at £57m due to house price growth. Costs have risen by £1.5m. The surplus is therefore £3.5m (£5m revenue uplift minus £1.5m cost increase). Under a 60:40 split, £2.1m is payable to the LPA as a commuted sum or additional affordable units. In your APC interview, demonstrate that you understand how to (a) calculate the surplus, (b) negotiate the split, (c) manage the interaction with Homes England grant, and (d) advise your board on the financial impact. Assessors want to see you applying the mechanism, not just describing it." },
    { type: "heading", text: "Key Components of a Late-Stage Review Clause" },
    { type: "paragraph", text: "A well-drafted late-stage VRM typically includes: (1) a trigger point — expressed as a percentage of private unit sales completions or a longstop date; (2) a defined methodology for the updated appraisal — referencing an agreed appraisal tool (often the GLA toolkit or Argus Developer), input assumptions such as benchmark land value (BLV), benchmark profit margin, and finance costs; (3) a surplus calculation formula — comparing the 'actual' position (using real sales data and certified cost accounts) against the 'benchmark' position (using the original appraisal assumptions inflated or static as agreed); (4) a surplus sharing ratio; (5) a cap — the maximum additional contribution, often expressed as 'up to policy-compliant affordable housing' (e.g., up to 50% if the original scheme only delivered 35%); and (6) a dispute resolution mechanism — typically referral to an independent surveyor acting as expert." },
    { type: "paragraph", text: "From a Latimer/Clarion perspective, the critical negotiation points at S106 drafting stage are: ensuring the benchmark profit reflects the RP's actual required return (which may be lower than a private developer's 15-20% on GDV — perhaps 6-8% for the affordable element); ring-fencing Homes England grant from the surplus calculation (grant should not artificially inflate the surplus); and ensuring the cap does not force conversion of units already allocated as private sale into affordable, which would undermine the cross-subsidy model. You should also negotiate for the costs used in the review to include actual Section 106/CIL contributions already paid, abnormal costs verified by a QS, and any inflation on build costs." },
    { type: "heading", text: "Interaction with Homes England Grant Funding" },
    { type: "paragraph", text: "This is an area where many candidates lack depth. Homes England AHP grant is awarded on the basis of a specific scheme profile: number of units, tenure split (Social Rent, Affordable Rent, Shared Ownership, etc.), grant rate per unit, and delivery milestones. If a late-stage VRM results in an obligation to deliver additional affordable units beyond the original consent, this may require a variation to the Homes England funding agreement. Critically, Homes England may not provide additional grant for those extra units if they were not in the original bid. The RP may therefore need to absorb the additional affordable units without grant subsidy — funded entirely from the commuted sum or from the scheme's own surplus. Alternatively, if the VRM results in a commuted sum payment rather than on-site units, the LPA typically holds that sum for off-site affordable housing delivery, and the RP has no direct claim on it." },
    { type: "callout", label: "APC Tip — Negotiation Strategy", text: "When drafting S106 heads of terms, advocate for any additional affordable housing obligation arising from a late-stage VRM to be delivered as a commuted sum rather than additional on-site units. This avoids disrupting the Homes England grant contract, the approved scheme design, and the RP's internal financial model. If on-site units are required, negotiate that the tenure is agreed at the review stage (not pre-determined) to allow the RP to select the most viable tenure given prevailing market conditions and Homes England priorities. Document your reasoning — assessors will reward evidence of proactive risk management." },
    { type: "heading", text: "Practical Process: Conducting a Late-Stage Review" },
    { type: "paragraph", text: "When the trigger point is reached, the developer (Latimer) must submit a review appraisal to the LPA within a defined window (often 3-6 months of the trigger). The appraisal should include: (a) actual private sales data — exchange prices, not asking prices — verified by solicitor confirmation or Land Registry data; (b) projected revenues for unsold units, using RICS Red Book compliant valuations or an agreed methodology; (c) certified actual costs from the project QS, broken down into construction, professional fees, S106/CIL, finance, marketing, and contingency; (d) the benchmark land value and benchmark profit margin as defined in the S106. The LPA (or their appointed viability consultant) reviews the submission. Common areas of dispute include: treatment of finance costs (actual vs. assumed), allocation of overheads and management fees (especially internal costs within the RP group), and whether projected sales for the remaining units should use the latest comparable evidence or a blended rate." },
    { type: "paragraph", text: "At Latimer, you should ensure the project QS provides a final cost certificate early, and that the sales team provides exchange data in a consistent format. Internal costs such as development management fees charged by Clarion to Latimer should be documented at arm's-length rates to withstand scrutiny. Any abnormal costs (e.g., remediation discovered during construction) should be evidenced with variation orders and independent verification." },
    { type: "heading", text: "Common Pitfalls and Dispute Areas" },
    { type: "paragraph", text: "Disputes most commonly arise over: (1) the benchmark profit level — if the original appraisal used 15% on GDV for the private element but the RP's actual required return is 6%, has the surplus been overstated?; (2) cost inflation — should actual costs be compared against the original estimate or an inflated version?; (3) phased schemes — where the VRM applies to the whole scheme but phases have been delivered over several years with different market conditions; (4) definition of 'surplus' — gross surplus vs. net surplus after tax; and (5) the cap — ensuring the additional obligation does not exceed the policy-compliant level. For Latimer, a specific risk is where Clarion's group treasury provides internal financing at rates different from market rates — the LPA may challenge the finance cost assumptions." },
    { type: "callout", label: "APC Tip — Demonstrating Level 3 Competence", text: "At Level 3, assessors expect you to provide reasoned advice. A strong answer would be: 'On a recent 150-unit scheme, the late-stage VRM was triggered at 80% sales. I led the preparation of the review appraisal, coordinating with the QS on certified costs and the sales team on exchange data. The initial LPA assessment identified a £1.8m surplus. I challenged this on the basis that (a) the finance cost assumption did not reflect our actual drawdown profile, (b) abnormal remediation costs of £400k had been excluded, and (c) projected revenues for the remaining 30 private units used peak market evidence that did not reflect current offers. After negotiation, the agreed surplus was £900k, payable as a commuted sum. I advised the board that this was a reasonable outcome that protected our IRR while meeting our obligations to the LPA.' This demonstrates advisory skill, technical accuracy, and commercial awareness." },
    { type: "heading", text: "Policy and Regulatory Context" },
    { type: "paragraph", text: "The NPPF (December 2024 revision) continues to support the use of viability review mechanisms where developments are permitted below policy-compliant affordable housing levels. Paragraph 58 and the associated PPG on Viability confirm that review mechanisms should reflect the recommended approach in national guidance but allow local flexibility. The GLA's Affordable Housing and Viability SPG remains the most detailed framework, requiring all 'Viability Tested Route' schemes to include both early-stage and late-stage reviews. Outside London, adoption varies — some LPAs (e.g., Bristol, Brighton, Oxford) have detailed SPDs on VRMs, while others rely on ad hoc negotiation. For a national RP like Clarion operating across multiple LPA areas, understanding this patchwork is essential." }
  ],
  summary: [
    "Late-stage VRMs compare actual outturn costs and revenues against original viability assumptions to capture surplus for additional affordable housing — typically triggered at 75-90% of private sales.",
    "The surplus sharing ratio is commonly 60:40 (LPA:developer) with an upward-only cap at policy-compliant affordable housing levels — negotiate hard on the benchmark profit and cost definitions at S106 drafting stage.",
    "Homes England AHP grant must be ring-fenced from the surplus calculation, and any additional affordable units arising from a VRM may not attract additional grant — flag this risk to your board early.",
    "Prepare for the review proactively: obtain QS cost certificates early, use verified exchange data for sales, document arm's-length internal charges, and evidence all abnormal costs with variation orders.",
    "At Level 3, demonstrate that you have personally led or advised on a VRM review — show the calculation, the negotiation, the outcome, and the advice given to your organisation."
  ],
  qa: [
    { q: "Can you explain how a late-stage viability review mechanism works in practice, using an example from your experience at Latimer?", a: "A late-stage VRM is triggered at a defined point (e.g., 75-80% of private sales) requiring the developer to submit an updated appraisal comparing actual revenues and costs against original assumptions. The surplus — actual profit above the benchmark profit level — is shared, typically 60:40 in favour of additional affordable housing. On a recent scheme, I prepared the review appraisal using QS-certified costs and verified sales exchange data, challenged the LPA's initial surplus figure by evidencing abnormal costs and a more realistic sales projection for remaining units, and negotiated the surplus down from £1.8m to £900k payable as a commuted sum. I advised the board this outcome protected our target IRR while meeting planning obligations." },
    { q: "How do you ensure Homes England grant funding is not adversely affected by a S106 viability review?", a: "I ensure that the S106 drafting explicitly excludes Homes England grant from the revenue inputs in the review appraisal, so it does not artificially inflate the surplus. If the VRM results in additional affordable units, I assess whether these can be accommodated within the existing AHP contract or require a variation. If additional grant is unavailable, I model the additional units on a nil-grant basis and advise whether the scheme can absorb them. I also advocate for commuted sums over on-site units where possible to avoid disrupting the grant contract's unit count and tenure profile." },
    { q: "What is the typical surplus sharing ratio in a late-stage VRM, and is this negotiable?", a: "The GLA SPG establishes a 60:40 split (60% to affordable housing, 40% retained by the developer), which has become the de facto standard in London. Outside London, ratios vary — some LPAs adopt 50:50 or bespoke splits. It is negotiable at S106 heads of terms stage. As an RP delivering affordable housing, I would argue for a higher developer retention (e.g., 50:50) on the basis that surplus retained by the RP is reinvested in affordable housing delivery across the programme, unlike a private housebuilder distributing profits to shareholders." },
    { q: "What are the key areas of dispute in a late-stage viability review, and how would you manage them?", a: "Common disputes include: the benchmark profit level (e.g., whether the RP's lower return distorts the surplus); treatment of finance costs (actual drawdown vs. modelled); inclusion of abnormal costs; and projected revenues for unsold units. I manage these by ensuring the S106 clearly defines the methodology and inputs at drafting stage, obtaining robust QS cost certification, using RICS-compliant valuations for unsold units, and engaging early with the LPA's viability consultant to agree data inputs before formal submission. If agreement cannot be reached, I invoke the dispute resolution clause — typically referral to an independent surveyor as expert." },
    { q: "Should a housing association prefer a commuted sum or additional on-site affordable units from a VRM uplift, and why?", a: "Generally, a commuted sum is preferable for the RP because: (1) it avoids changing the scheme design and unit mix post-construction, which may be impractical; (2) it does not conflict with the Homes England grant contract which specifies a fixed unit count and tenure; (3) it provides the LPA with a flexible fund for off-site affordable delivery; and (4) it avoids the RP taking on additional affordable units without corresponding grant subsidy. However, if the LPA insists on on-site units, I would negotiate that the tenure is agreed at the review stage to match current Homes England priorities and the RP's financial capacity." }
  ],
  news: [
    { tag: "S106 / Viability", headline: "GLA publishes updated Viability Tested Route guidance tightening late-stage review requirements", body: "The Greater London Authority has issued revised supplementary guidance strengthening late-stage viability review requirements for all Viability Tested Route schemes, mandating independent cost verification and standardised surplus calculation templates. The changes respond to criticism that developers were gaming cost assumptions to minimise surplus payments." },
    { tag: "Affordable Housing", headline: "Homes England confirms AHP 2026-31 programme will require grant clawback alignment with S106 VRMs", body: "Homes England's new Affordable Homes Programme 2026-31 framework includes provisions requiring registered providers to demonstrate how S106 viability review obligations interact with grant-funded schemes. RPs must now include VRM risk assessments in all new AHP funding bids, ensuring grant is not double-counted as scheme revenue in review appraisals." },
    { tag: "Planning Reform", headline: "Bristol City Council adopts SPD mandating viability review mechanisms on all major residential schemes", body: "Bristol has become one of the first non-London authorities to mandate both early-stage and late-stage viability review mechanisms on all residential schemes of 50+ units delivering below policy-compliant affordable housing. The SPD adopts a 60:40 surplus sharing ratio and requires reviews to be conducted using the RICS Financial Viability in Planning guidance (2021)." }
  ]
};
